pudding-keep-in-touch/keep-in-touch-fe

src/app/message/send/[variety]/write/page.tsx
src/app/message/send/layout.tsx
src/app/message/send/select/_components/nextButton.tsx
src/app/message/send/select/page.tsx

…n functionality
Enhance message send layout with header and back navigation
|기능|스크린샷|
|--|--|
|||

:lipstick: Enhance message send layout with header and back navigation

---

.github/workflows/run_test.yml
.gitignore
package.json
pnpm-lock.yaml
setup-tests.ts
src/app/message/send/[variety]/write/_components/form.test.tsx
tsconfig.json
vitest.config.ts

Enhance testing setup with Vitest and add form tests for validation
|기능|스크린샷|
|--|--|
|||

:white_check_mark: Enhance testing setup with Vitest

---

src/app/auth/callback/page.tsx
src/app/home/_components/messagePreview.tsx
src/app/home/_hooks/useCurrentMessage.tsx
src/app/home/page.tsx
src/shared/lib/api.ts
src/shared/lib/apiClient.ts
src/shared/types/index.ts

:sparkles: Finished Home screen and login logic

---

src/app/home/_hooks/useCurrentMessage.tsx
src/app/home/page.tsx
src/shared/lib/apiClient.ts

fix: Fix Login Process

---

src/app/home/_hooks/useCurrentMessage.tsx
src/app/home/page.tsx
src/shared/lib/api.ts

fix: Add the user id search param

---

src/app/home/page.tsx

feat: Change the param name (sendDmList)

---

src/app/home/page.tsx

fix: Fix checking response

---

src/app/home/page.tsx
src/shared/api/baseQuery.ts
src/shared/config.ts
src/shared/lib/apiClient.ts

develop config setting

---

src/shared/api/baseQuery.ts

develop config setting 2

---

src/app/auth/callback/page.tsx
src/app/home/_components/linkShareButton.tsx
src/app/home/_components/messagePreview.tsx
src/app/home/page.tsx
src/app/message/[variety]/[userId]/[detail]/_components/sendButton.tsx
src/app/message/[variety]/[userId]/_components/message.tsx
src/app/message/send/[userId]/select/_components/selectBoard.tsx
src/entities/message/api/queries.ts

QA issue feedback correction processing

---

src/app/home/_components/linkShareButton.tsx
src/app/message/[variety]/[userId]/[detail]/_components/sendButton.tsx
src/app/message/send/[userId]/[variety]/completion/_components/preview.tsx
src/app/message/send/[userId]/complete/[dmId]/_components/moveButton.tsx
src/shared/config.ts

QA issue feedback correction processing2

QA issue feedback correction processing2

---

src/app/auth/callback/page.tsx
src/app/message/send/[userId]/[variety]/completion/_components/buttons.tsx
src/app/message/send/[userId]/[variety]/completion/_components/submitButton.tsx

Fix send message parameters
Fix send message parameters
Fix send message parameters

Fix send message parameters

---

src/app/message/send/[userId]/[variety]/completion/_components/buttons.tsx

Fix send message parameters 
Fix send message parameters 
Fix send message parameters

Fix send message parameters2

---

src/app/home/_components/messagePreview.tsx

QA issue feedback correction processing3
QA issue feedback correction processing3
QA issue feedback correction processing3
QA issue feedback correction processing3

QA issue feedback correction processing3

---

src/app/message/[variety]/[userId]/_components/message.tsx

QA issue feedback correction processing4
QA issue feedback correction processing4
QA issue feedback correction processing4
QA issue feedback correction processing4

QA issue feedback correction processing4

---

src/app/login/page.tsx
src/app/page.tsx

Fix Main UI Style 
Fix Main UI Style 
Fix Main UI Style

Fix Main UI Style 

---

src/app/home/layout.tsx

Hotfix Login Error
Hotfix Login Error
Hotfix Login Error

Hotfix Login Error

---

src/shared/provider/Auth/index.tsx

로그인 내부에서 token 검증 처리 추가
로그인 내부에서 token 검증 처리 추가
로그인 내부에서 token 검증 처리 추가

Hotfix Login Error2

---

src/shared/provider/Auth/index.tsx

Fix Login Logic
Fix Login Logic
로그인 상태 로직 내부에서 error 발생시, getLoginUrl 로 redirectUrl 처리할 수 있도록 수정

Fix Login Logic

---

src/shared/config.ts

Add redirectUrl when calling callback API
Add redirectUrl when calling callback API
Add redirectUrl when calling callback API

Add redirectUrl when calling callback API

---

src/app/layout.tsx

Hotfix issue

---

src/app/layout.tsx
src/app/message/send/[userId]/[variety]/_components/form.test.tsx

Add meta image image test
Add meta image image test
Add meta image image test

Add meta image test

---

pnpm-lock.yaml

develop > main 백포팅

---

.github/workflows/build-and-push-image.yml
.github/workflows/run_test.yml

git action Build and Push Docker Image branch를 release/v2로 변경
run-test.yml 파일에서 테스트가 release/v2 브랜치에 대해 트리거되도록 변경
git action Build and Push Docker Image branch를 release/v2로 변경
run-test.yml 파일에서 테스트가 release/v2 브랜치에 대해 트리거되도록 변경

fix : git action docker image push branches fix

---

src/app/messagebox/inbox/page.tsx
src/app/messagebox/page.tsx
src/features/messagebox/_detail/api/detailQuery.ts
src/features/messagebox/_detail/model/messagebox.types.ts
src/features/messagebox/_detail/ui/layouts/InboxLayout.tsx
src/features/messagebox/model/messagebox.types.ts
src/features/messagebox/ui/InboxList.tsx

- fetch messagebox mockdata
- api props 적용
- api에 따른 폴더 위치 변경
|기능|스크린샷|
|--|--|
|||

[feat] fetch messagebox data using mockData & 폴더 구조 변경

---

src/app/auth/callback/page.tsx
src/features/auth/context/AuthProvider.tsx
src/features/home/ui/scrollToTopButton.tsx
src/features/login/ui/googleButton.tsx
src/features/login/ui/login.tsx
src/shared/config/env.ts
src/shared/hooks/useScrollToTop.tsx
src/shared/ui/layouts/ScrollLayout.tsx

Auth 개선, 홈 내 스크롤 이슈 처리, 로그인 하단 버튼 web safari 이슈 처리
Auth 개선, 홈 내 스크롤 이슈 처리, 로그인 하단 버튼 web safari 이슈 처리
Auth 개선, 홈 내 스크롤 이슈 처리, 로그인 하단 버튼 web safari 이슈 처리
|기능|스크린샷|
|--|--|
|||
🔥 `feat/mainApi`를 바라보고 있는 브랜치입니다. 리뷰 후 `feat/mainApi` 머지 예정입니다!

[Fix] Auth 개선, 홈 내 스크롤 이슈 처리, 로그인 하단 버튼 web safari 이슈 처리

---

src/app/auth/callback/page.tsx

Auth Callback 로직 수정
Auth Callback 로직 수정
|기능|스크린샷|
|--|--|
|||

[Fix] Auth Callback 로직 수정

---

src/features/auth/context/AuthProvider.tsx
src/features/questions/hooks/query/useNicknameQuery.tsx
src/features/questions/hooks/query/useQuestionQuery.tsx
src/features/questions/ui/QuestionListPage.tsx
src/features/questions/ui/QuestionPage.tsx
src/shared/api/baseQuery.ts

로컬에서 리다이렉트 테스트가 불가능하여... 이 pr 머지 빠르게 하고 이후 작업 진행하겠습니다
|기능|스크린샷|
|--|--|
|||

[Feature] 질문 목록, 질문 api 연동

---

src/app/auth/callback/page.tsx
src/features/home/ui/questionListHeader.tsx
src/shared/config/env.ts

Auth Callback Fix
Auth Callback Fix
Auth Callback Fix
|기능|스크린샷|
|--|--|
|||

[Fix] Auth Callback Fix

---

src/app/questions/[questionId]/layout.tsx

auth 관련 테스트1
|기능|스크린샷|
|--|--|
|||

[Test] auth 관련 테스트1

---

src/app/home/[userId]/layout.tsx
src/app/home/[userId]/page.tsx
src/app/home/[userId]/question/[questionId]/page.tsx
src/app/home/[userId]/write/page.tsx
src/app/login/layout.tsx
src/app/page.tsx
src/app/profile/[userId]/page.tsx
src/features/home/api/api.ts
src/features/home/home.tsx
src/features/home/questionDetail.tsx
src/features/home/ui/completeButton.tsx
src/features/home/ui/linkShareButton.tsx
src/features/home/ui/messagePreview.tsx
src/features/home/ui/questionBanner.tsx
src/features/home/ui/questionListHeader.tsx
src/features/home/ui/questionsCard.tsx
src/features/home/ui/questionsList.tsx
src/features/home/ui/scrollHome.tsx
src/features/home/writeQuestion.tsx
src/features/profile/ui/profile.tsx
src/shared/components/Button.tsx
src/shared/components/nav.tsx
src/shared/ui/layouts/DefaultLayout.tsx
src/shared/ui/layouts/QuestionLayout.tsx
src/shared/ui/layouts/ScrollLayout.tsx
tailwind.config.ts

내부 QA 피드백 1차 수정
내부 QA 피드백 1차 수정
|기능|스크린샷|
|--|--|
|||

[Fix] 내부 QA 피드백 1차 수정

---

src/app/message/[type]/[userId]/page.tsx
src/app/message/send/[userId]/[variety]/complete/[dmId]/page.tsx
src/app/message/send/[userId]/[variety]/preview/page.tsx
src/app/message/send/[userId]/layout.tsx
src/app/questions/[questionId]/layout.tsx
src/app/questions/messages/layout.tsx
src/features/message/_send/_complete/ui/moveButton.tsx
src/features/message/_send/_completion/ui/buttons.tsx
src/features/message/_send/_completion/ui/preview.tsx
src/features/message/_send/_completion/ui/submitButton.tsx
src/features/message/_send/_write/ui/messageInput.tsx
src/features/message/_send/api/sendMutation.ts
src/features/message/_send/model/form.test.tsx
src/features/message/api/messageQueries.ts
src/features/message/ui/message.tsx
src/features/questions/hooks/query/useQuestionQuery.tsx
src/features/questions/ui/CompletePage.tsx
src/features/questions/ui/PreviewPage.tsx
src/features/questions/ui/QuestionListPage.tsx
src/features/questions/ui/QuestionPage.tsx
src/features/questions/ui/button/QuestionButton.tsx
src/features/questions/ui/button/SendButton.tsx
tsconfig.json

- api 연동을 우선적으로 구현하느라 코드가 지저분합니다. 빠른 시일 내로 깔끔한 코드로 만들 수 있도록 하겠습니다🥹
- 불필요하다고 생각되는 컴포넌트에 주석처리를 해놨는데 혹여 다른 분께서 쓰시는 코드였다면... 죄송합니다
|기능|스크린샷|
|--|--|
|||

[Feature] 메시지 전송 api 연동, 로그인 후 리다이렉트 로직 수정

---

src/app/questions/messages/layout.tsx
src/features/questions/hooks/query/useNicknameQuery.tsx
src/features/questions/ui/QuestionListPage.tsx
src/shared/components/Sppiner.tsx

- 초기 진입 시에 닉네임을 불러오지 못하는 이슈가 있어서 localstorage나 queryclient 중 데이터가 있다면 불러오는 것으로 수정했습니다.
- 로컬에서는 layout 쪽에만 적용해도 다른 데이터가 불러와지는 것으로 확인 됐는데 개발 서버에서 테스트 시에 다른 데이터를 못불러온다면 해당 로직을 다른 곳에도 추가할 예정입니다.
- 데이터를 가져오는 동안 spinner 처리를 추가했습니다.
- spinner 컴포넌트를 가운데 정렬 하는 방식으로 css 추가했습니다.
|기능|스크린샷|
|--|--|
|||

[Fix] 리다이렉트 후 데이터 불러오는 방식 수정

---

src/app/auth/callback/page.tsx
src/app/home/[userId]/page.tsx

로그인 후 무한 로딩 이슈 처리
|기능|스크린샷|
|--|--|
|||

[Hotfix] 로그인 후 무한 로딩 이슈 처리

---

src/features/auth/context/AuthProvider.tsx

로그인 후 무한 로딩 이슈 처리2
|기능|스크린샷|
|--|--|
|||

[Hotfix] 로그인 후 무한 로딩 이슈 처리2

---

src/app/auth/callback/page.tsx
src/app/home/[userId]/page.tsx
src/features/auth/context/AuthProvider.tsx

로그인 후 무한 로딩 이슈 처리3
|기능|스크린샷|
|--|--|
|||

[Hotfix] 로그인 후 무한 로딩 이슈 처리3

---

src/app/auth/callback/page.tsx
src/app/home/[userId]/page.tsx
src/app/page.tsx
src/features/auth/context/AuthProvider.tsx

로그인 후 무한 로딩 이슈 처리 테스트
|기능|스크린샷|
|--|--|
|||

[Hotfix] 로그인 후 무한 로딩 이슈 처리 테스트

---

src/app/page.tsx

로그인 후 무한 로딩 이슈 처리4
|기능|스크린샷|
|--|--|
|||

[Hotfix] 로그인 후 무한 로딩 이슈 처리4

---

src/features/auth/context/AuthProvider.tsx
src/features/login/ui/login.tsx

로그인 후 무한 로딩 이슈 처리 테스트 2
|기능|스크린샷|
|--|--|
|||

[Hotfix] 로그인 후 무한 로딩 이슈 처리 테스트 2

---

src/features/login/ui/login.tsx

로그인 페이지에서 로딩 관련 명확한 종료 처리 추가
|기능|스크린샷|
|--|--|
|||

[Hotfix] 로그인 페이지에서 로딩 관련 명확한 종료 처리 추가

---

src/features/login/ui/login.tsx

로그인 후 무한 로딩 이슈 처리7
|기능|스크린샷|
|--|--|
|||

[Hotfix] 로그인 후 무한 페이지 이슈 처리7

---

src/app/auth/callback/page.tsx
src/features/auth/context/AuthProvider.tsx
src/features/login/ui/login.tsx

로그인 후 무한 로딩 이슈 처리9
|기능|스크린샷|
|--|--|
|||

[Hotfix] 로그인 후 무한 로딩 이슈 처리9

---

src/features/login/ui/login.tsx

login 관련 분기처리 수정
|기능|스크린샷|
|--|--|
|||

[Fix] login 관련 분기처리 수정

---

src/app/auth/callback/page.tsx
src/app/page.tsx
src/features/auth/context/AuthProvider.tsx

인증 관련 로직 디버깅 코드 추가 테스트
|기능|스크린샷|
|--|--|
|||

[Test] 인증 관련 로직 디버깅 코드 추가 테스트

---

src/features/auth/context/AuthProvider.tsx

인증 관련 로직 디버깅3
|기능|스크린샷|
|--|--|
|||

[Test] 인증 관련 로직 디버깅3

---

src/app/auth/callback/page.tsx
src/app/home/[userId]/page.tsx
src/app/page.tsx
src/features/auth/context/AuthProvider.tsx
src/features/home/api/api.ts
src/features/login/ui/login.tsx
src/features/message/_detail/api/detailQuery.ts
src/features/message/_detail/ui/layouts/MessageDetailLayout.tsx
src/features/message/_detail/ui/sendButton.tsx
src/features/message/api/messageQueries.ts
src/features/messagebox/_detail/api/detailQuery.ts
src/shared/api/baseQuery.ts
src/shared/hooks/useAuth.ts
src/shared/utils/cookieUtils.ts
src/shared/utils/tokenUtils.ts

인증 관련 로직 디버깅4
|기능|스크린샷|
|--|--|
|||

[Test] 인증 관련 로직 디버깅4

---

src/shared/components/QuestionBox.tsx

[Feature] 질문 상자에 한 줄 이상 시 hidden 추가

---

src/features/home/api/api.ts
src/features/home/ui/tooltip.tsx
src/shared/ui/layouts/DefaultLayout.tsx

내부 QA 피드백 5차 수정 
|기능|스크린샷|
|--|--|
|||

[Fix] 내부 QA 피드백 5차 수정 

---

src/features/home/writeQuestion.tsx

질문 작성하기 페이지 버튼 스타일 위치 수정
|기능|스크린샷|
|--|--|
|||

[Fix] 질문 작성하기 페이지 버튼 스타일 위치 수정

---

.dockerignore
Dockerfile
package.json
pnpm-lock.yaml
src/app/auth/callback/page.tsx
src/app/login/page.tsx
src/app/questions/page.tsx

- `pnpm run build` 시 발생하는 error 해결
- static file 생성 시 발생하는 "document is not defined" 에러 해결
- Suspense 및 force-dynamic route로 해결
- Dockerfile multi-staged build로 개선 및 `pnpm start` 커맨드 사용하도록 변경
개선 - 1.44GB
기존 - 1.87GB
|기능|스크린샷|
|--|--|
|||

[Fix] fix build issue
